from firewall.helpers.exceptions.plumbum import ProcessExecutionError
